
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const CHANGE_ORDER_SUMMERY_MODAL = 'CHANGE_ORDER_SUMMERY_MODAL'
export const CHECK_AUTH = 'CHECK_AUTH'
export const FETCH_INGREDIENT = 'FETCH_INGREDIENT'
export const FETCH_ORDERS = 'FETCH_ORDERS'